apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: dex
    role: worker
  name: dex-worker
spec:
  replicas: {{.WorkerCount}}
  selector:
    app: dex
    role: worker
  template:
    metadata:
      labels:
        app: dex
        role: worker
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-worker
            env:
              - name: DEX_WORKER_ISSUER
                value: {{.K8sHost}}
              - name: DEX_WORKER_DB_URL
                value: {{.PostgresUrl}}
              - name: DEX_WORKER_EMAIL_CFG
                value: /opt/dex/email/emailer.json
              - name: DEX_WORKER_LISTEN
                value: http://0.0.0.0:5556
            command:
              - "sh"
              - "-c"
              - "/opt/dex/bin/dexctl --db-url $DEX_WORKER_DB_URL set-connector-configs /etc/dex/connectors-json &&
              /opt/dex/bin/dex-worker --key-secrets=$(cat /etc/dex/key-secrets)"
            ports:
            - containerPort: 5556
              name: worker-port
            livenessProbe:
              httpGet:
                path: /health
                port: 5556
              initialDelaySeconds: 15
              timeoutSeconds: 1
            volumeMounts:
              - name: dex
                mountPath: "/etc/dex"
                readOnly: true
      volumes:
        - name: dex
          secret:
            secretName: "dex"
