apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: dex
    role: overlord
  name: dex-overlord
spec:
  replicas: 1
  selector:
    app: dex
    role: overlord
  template:
    metadata:
      labels:
        app: dex
        role: overlord
    spec:
      containers:
          - image: quay.io/coreos/dex
            name: dex-overlord
            env:
              - name: DEX_OVERLORD_DB_URL
                value: {{.PostgresUrl}}
              - name: DEX_OVERLORD_ADMIN_LISTEN
                value: http://0.0.0.0:5557
            command:
              - "sh"
              - "-c"
              - "/opt/dex/bin/dex-overlord  --key-secrets=$(cat /etc/dex/key-secrets)"
            ports:
            - containerPort: 5557
              name: overlord-port
            livenessProbe:
              httpGet:
                path: /health
                port: 5557
              initialDelaySeconds: 15
              timeoutSeconds: 1
            volumeMounts:
              - name: dex
                mountPath: "/etc/dex"
                readOnly: true
      volumes:
        - name: dex
          secret:
            secretName: "dex"
